### ISSUE TITLE
Mac Outlook John Doe Chrome

### ISSUE THREAD

**Issue by big610** [filippo-liverani/john-doe-chrome#2]
Late January 3 2018, My Mac Outlook Password became a wrong password. My Outlook password opened fine with Safari, Mozilla & Windows Chrome with John Doe enabled. I then disabled John Doe Chrome, Outlook Mac then was able to acknowledge my password. Please see what Microsoft did approximately late 01/03/18 or early 01/04/18 to Mac Outlook. Hopefully you will be able to write an update. By the way Microsoft changed the code to Outlook, effecting 3rd party email apps 12/12/18. Please let me know, when an update is ready to be tested.

**Comment by filippo-liverani** [comment]
Hey, unfortunately Microsoft `live.com` authentication uses multiple domains and checks referer header during login. John Doe Chrome sets that header to match the one of the destination URL for privacy reasons and it won't work with that authentication check.

I am afraid you should disable John Doe Chrome during any `live.com` logins and re-enable it afterwards.

**Comment by big610** [comment]
Thanks for the quick response.


I have an update.

Decided I like what your doing, will keep John Doe enabled on Mac, use Chrome New Incognito Window when needing Outlook.

I mistakingly went into Mac Chrome & John Doe enabled works.

[Windows John Doe still fine with Outlook]

Also,
I test for the Developer of Howard email Mac & Windows Open Source, and he had to re-write the entire app, when I found the Microsoft problems which began Patch Tuesday the 2nd week of December.

Thanks
________________________________

**Comment by filippo-liverani** [comment]
👍
