### ISSUE TITLE
Remove JS API screen and window spoofing

### ISSUE THREAD

**Issue by gameb0y** [filippo-liverani/john-doe-chrome#3]
why remove? :-1:

**Comment by filippo-liverani** [comment]
Sorry but it was to aggressive and broke a lot of websites.
I think the best solution right now is to leave John Doe Chrome always enabled and to use something like [ScriptSafe](https://chrome.google.com/webstore/detail/scriptsafe/oiigbmnaadbkfbmpbfijlflahbdbdgdf) when you want to block JS APIs on an untrusted website.
